# -*- coding: utf-8 -*-
"""tf18wine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qi7Dc9JVdbYAbb35lMbbYhE2B2dbBvK-
"""

# wine dataset으로 레드/화이트 와인 분류 모델
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, BatchNormalization, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

wdf=pd.read_csv('https://raw.githubusercontent.com/pykwon/python/refs/heads/master/testdata_utf8/wine.csv', header=None)
# print(wdf.head(3))
# print(wdf.info())
# print(wdf.iloc[:,12].unique())      # 라벨 값 확인 → [1 0] (예: red/white)
# print(len(wdf[wdf.iloc[:,12]==0]))  # 4898
# print(len(wdf[wdf.iloc[:,12]==1]))  # 1599

dataset=wdf.values
# print(dataset)
x=dataset[:,0:12]
y=dataset[:,-1]

np.set_printoptions(suppress=True)  # 지수표기 억제(소수 그대로 보이도록)
print(x[:3])  # 첫 3행의 입력 특징 미리보기
print(y[:3])  # 첫 3행의 라벨 미리보기
print('=='*20)

# 학습/테스트 분할
# - test_size=0.3 : 30%를 테스트로
# - shuffle=True  : 분할 전에 셔플
# - random_state=12 : 재현성
# - 라벨 불균형(대략 4898 vs 1599)이 있으므로, 보통은 stratify=y 권장
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,shuffle= True,random_state=12, stratify=y)   # train_test_split은 과적합 방지 방

print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)  # (4547, 12) (1950, 12) (4547,) (1950,)
print(x_train[:3])   # 학습용 특징 일부
print(y_train[:3])   # 학습용 라벨 일부

# 모델 생성
model=Sequential()
model.add(Input(shape=(12,)))                   # 입력층: 특징 개수 12개(전처리에서 X가 12열이었음) / shape=(12,)은 각 샘플이 길이 12의 벡터라는 의미 (배치 차원 None은 자동)
model.add(Dense(units=32, activation='relu'))   # 은닉층 1: 유닛 32, ReLU 활성화 → 비선형 표현력 확보 / 파라미터 수: (입력 12 + 바이어스 1) * 32 = 416
model.add(Dropout(rate=0.2))                    # 드롭아웃: 학습 시 20% 뉴런을 무작위로 끄기(과적합 완화)
model.add(BatchNormalization())                 # 배치 정규화, 역전파시 기울기 소실 및 폭주 방지, cnn 등에서 특히 효과있음
model.add(Dense(units=16, activation='relu'))   # 은닉층 2: 유닛 16, ReLU / 파라미터 수: (이전 유닛 32 + 바이어스 1) * 16 = 528
model.add(Dropout(rate=0.1))                    # 드롭아웃(재차 과적합 방지)
model.add(BatchNormalization())
model.add(Dense(units=8, activation='relu'))    # 은닉층 3: 유닛 8, ReLU / 파라미터 수: (이전 유닛 16 + 바이어스 1) * 8 = 136
model.add(Dense(units=1, activation='sigmoid')) # 출력층: 유닛 1, 시그모이드 → 양성 클래스 확률 p∈[0,1] (이진 분류의 표준) / 파라미터 수: (이전 유닛 8 + 바이어스 1) * 1 = 9
print(model.summary())

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])
# fit()전에 model score 확인
loss,acc=model.evaluate(x_train,y_train,verbose=0)
print('훈련 전 모델 정확도 : {:5.2f}%'.format(100*acc))  # 훈련 전 모델 정확도 : 74.86%

# 모델 저장 폴더 설정
MODEL_DIR='./model/'
if not os.path.exists(MODEL_DIR):
    os.mkdir(MODEL_DIR)

modelpath='model/{epoch:02d}_{val_loss:.4f}.keras'
# modelpath='abc.keras'

# 모델 학습과정에서 특정 기준에 따라 자동으로 모델을 저장하는 callback
chkpoint=ModelCheckpoint(
    filepath=modelpath,
    monitor='val_loss',   # - monitor='val_loss'     : 검증 손실을 기준으로 성능 판단(낮을수록 좋음)
    mode='auto',          # - mode='auto'            : 지표 방향 자동 추론(여기선 'min'과 동일하게 동작)
    save_best_only=True   # - save_best_only=True    : 성능이 향상될 때만 파일 저장(디스크 낭비 방지)
)  # val_loss > min / 기본mode=auto


early_stop=EarlyStopping(
    monitor='val_loss',   # - monitor='val_loss' : 검증 손실이 더 이상 좋아지지 않으면
    patience=5            # - patience=5         : 5에포크 연속 개선이 없을 때 학습 중단
)

history = model.fit(
    x_train, y_train,
    validation_split=0.2,   # - validation_split=0.2 : 훈련 데이터의 20%를 검증용으로 자동 분리
    epochs=1000,            # - epochs=1000          : 최대 1000에포크 시도(조기종료로 실제는 더 일찍 끝남)
    batch_size=64,          # - batch_size=64        : 미니배치 크기
    callbacks=[early_stop, chkpoint],   # - callbacks=[...]      : 조기종료 + 체크포인트 적용
    verbose=2               # - verbose=2            : 에포크별 로그 한 줄 출력
)

loss, acc=model.evaluate(x_test,y_test,batch_size=64,verbose=0) # - evaluate 반환: [loss, acc] (metrics에 따라 구성 달라짐)
print('훈련 후 모델 정확도 : {:5.2f}%'.format(100*acc))  # 훈련 후 모델 정확도 : 97.38%

# 시각화
epoch_len=np.arange(len(history.epoch))

plt.plot(epoch_len,history.history['val_loss'],label='val_loss')
plt.plot(epoch_len,history.history['loss'],label='loss',c='red')
plt.xlabel('epochs')
plt.ylabel('loss')
plt.legend(loc='best')
plt.show()

plt.plot(epoch_len,history.history['val_acc'],label='val_acc')
plt.plot(epoch_len,history.history['acc'],label='acc',c='red')
plt.xlabel('epochs')
plt.ylabel('acc')
plt.legend(loc='best')
plt.show()

from types import new_class
# best모델로 예측
from tensorflow.keras.models import load_model
model=load_model(MODEL_DIR+'20_0.0747.keras')

new_data=x_test[:5,:]
print(new_data)
pred=model.predict(new_data)
print('예측결과 : ',np.where(pred>=0.5,1,0).ravel())